/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNotifyInscricaoRouteImport } from './routes/api/public/notify-inscricao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyInscricaoRoute =
  ApiPublicNotifyInscricaoRouteImport.update({
    id: '/api/public/notify-inscricao',
    path: '/api/public/notify-inscricao',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/notify-inscricao': typeof ApiPublicNotifyInscricaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/notify-inscricao': typeof ApiPublicNotifyInscricaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/notify-inscricao': typeof ApiPublicNotifyInscricaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/notify-inscricao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/notify-inscricao'
  id: '__root__' | '/' | '/api/public/notify-inscricao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicNotifyInscricaoRoute: typeof ApiPublicNotifyInscricaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-inscricao': {
      id: '/api/public/notify-inscricao'
      path: '/api/public/notify-inscricao'
      fullPath: '/api/public/notify-inscricao'
      preLoaderRoute: typeof ApiPublicNotifyInscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicNotifyInscricaoRoute: ApiPublicNotifyInscricaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
